version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'latest'
    open-pull-requests-limit: 50
    schedule:
      interval: 'monthly'
      timezone: "Asia/Shanghai"
      time: '09:00'

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'latest'
    open-pull-requests-limit: 50
    schedule:
      interval: 'monthly'
      timezone: "Asia/Shanghai"
      time: '09:00'
    ignore:
      - dependency-name: '@babel*'
      - dependency-name: '@storybook*'
      - dependency-name: 'eslint*'
      - dependency-name: '@typescript-eslint*'